### ISSUE TITLE
性能损耗的疑问

### ISSUE THREAD

**Issue by zhongweikang** [baidu/bfe-book#20]
https://github.com/baidu/bfe-book/blob/version1/design/ideas/ideas.md?plain=1#L60

这里描述了两点`bfe`相比于`nginx`性能差的原因，但感觉网络模型也是非常重要的一点

`nginx `的每个`worker`是基于`reactor`的单线程模型

对与`bfe`而言，是否是每来一个连接，都要开一个新的协程处理请求？
比如这里：https://github.com/bfenetworks/bfe/blob/develop/bfe_server/http_server.go#L101

当来了一波并发，基于上述`goroutine-per-connection模型`，要开大量的协程分别处理这些请求，此时`GPM`的调度，`cpu`上下文切换，都需要消耗大量`cpu`时间，导致性能降低

上述的描述基于主观猜测，望指正~

**Comment by mileszhang2016** [comment]
BFE使用的是Go语言的协程（即 Go routine）。
Go routine的创建和销毁的成本极低，调度方面也不涉及CPU上下文的切换，开销之小远非linux thread可比。
