### ISSUE TITLE
BFE的转发模型 有些表述有问题？

### ISSUE THREAD

**Issue by ccqy66** [baidu/bfe-book#7]
```
步骤 5：确定HTTP请求所属的租户

多租户支持是BFE根据云场景所设计提供的能力。目前BFE可以根据HTTP请求头中的Host字段或HTTP请求的目标IP地址来确定租户。

在本案例中，针对HTTP请求头中demo.example.com域名，BFE找到对应的租户为demo。
```
这个时候拿到的http请求的目标ip地址是没有办法确定租户吧，因为这个时候拿到的http请求的目标ip地址要么是bgw的ip或者是被bgw改写的bfe的ip。

**Comment by mileszhang2016** [comment]
BFE上游的四层负载均衡器可以通过一些方式将VIP地址（即这里说的“HTTP请求的目标IP地址”）传递给BFE。
比较常见的方式是通过Proxy Protocol。也有一些私有的实现方式（如：将VIP携带在TCP  Options中）
